name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  configure_python:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip

  configure_aws:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

  update_lambda_test:
    runs-on: ubuntu-latest
    needs: [checkout, configure_aws]
    defaults:
      run:
        working-directory: src/lambda
    steps:
      - name: Check working-directory
        run: |
          pwd
          ls -la
          cd ..
          pwd
          ls -la
      - name: Create test zip file 
        run: |
          cd src/lambda/test
          pwd
          ls -la
          zip -r test.zip .
      - name: Update test function
        run: |
          aws lambda update-function-code \
          --function-name test \
          --zip-file fileb://src/lambda/test/test.zip
