name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -la

  configure_dep:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          sudo apt-get install awscli
      - run: |
          pwd
          ls -la

  update_lambda_test:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update only on changes in src/lambda/test
        id: check-changes
        run: |
          if [ -n "$(git diff --name-only ${{ github.sha }}..$GITHUB_SHA | grep '^src/lambda/test')" ]; then
            echo "Changes detected in src/lambda/test. Proceeding with the workflow."
          else
            echo "No changes in src/lambda/test. Skipping the workflow."
            exit 1
          fi
      - name: Configure AWS Credentials
        if: success() && steps.check-changes.outcome == 'success'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create test zip file 
        if: success() && steps.check-changes.outcome == 'success'
        run: |
          cd src/lambda/test
          zip -r test.zip .
      - name: Update test function
        if: success() && steps.check-changes.outcome == 'success'
        run: |
          aws lambda update-function-code \
          --function-name test \
          --zip-file fileb://src/lambda/test/test.zip
      - name: Clean up check-changes fail
        if: steps.check-changes.outcome != 'success'
        run: |
          echo "Cleaning up failure in src/lambda/test job"
