name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -la

  configure_dep:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          sudo apt-get install awscli
      - run: |
          pwd
          ls -la

  update_lambda_test:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create test zip file 
        run: |
          cd src/lambda/test
          zip -r test.zip .
      - name: Update test function
        run: |
          aws lambda update-function-code \
          --function-name test \
          --zip-file fileb://src/lambda/test/test.zip \
          --publish


  update_lambda_getS3Object:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create getS3Object zip file 
        run: |
          cd src/lambda/getS3Object
          zip -r getS3Object.zip .
      - name: Update getS3Object function
        run: |
          aws lambda update-function-code \
          --function-name getS3Object \
          --zip-file fileb://src/lambda/getS3Object/getS3Object.zip \
          --publish

  update_lambda_cognitotest:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create getS3Object zip file 
        run: |
          cd src/lambda/cognitotest
          zip -r cognitotest.zip .
      - name: Update cognitotest function
        run: |
          aws lambda update-function-code \
          --function-name cognitotest \
          --zip-file fileb://src/lambda/cognitotest/cognitotest.zip \
          --publish

  update_lambda_create_account:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Substitute secrets in password.py
        run: |
          sed -i "s/rds_host = \"secret\"/rds_host = \"${{ secrets.RDS_HOST }}\"/g" src/lambda/login/password.py
          sed -i "s/db_username = \"secret\"/db_username = \"${{ secrets.DB_USERNAME }}\"/g" src/lambda/login/password.py
          sed -i "s/db_password = \"secret\"/db_password = \"${{ secrets.DB_PASSWORD }}\"/g" src/lambda/login/password.py
          sed -i "s/db_name = \"secret\"/db_name = \"${{ secrets.DB_NAME }}\"/g" src/lambda/login/password.py
          sed -i "s/userpool = \"secret\"/userpool = \"${{ secrets.USERPOOL }}\"/g" src/lambda/login/password.py
      - name: Create create_account zip file 
        run: |
          cd src/lambda/create_account
          zip -r create_account.zip .
      - name: Update cognitotest function
        run: |
          aws lambda update-function-code \
          --function-name create_account \
          --zip-file fileb://src/lambda/create_account/create_account.zip \
          --publish

  update_lambda_rekognition_image_analysis:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create rekognition_image_analysis zip file
        run: |
          cd src/lambda/rekognition_image_analysis
          zip -r rekognition_image_analysis.zip . 
      - name: Update rekognition_image_analysis function
        run: |
          aws lambda update-function-code \
          --function-name rekognition_image_analysis \
          --zip-file fileb://src/lambda/rekognition_image_analysis/rekognition_image_analysis.zip \
          --publish

  update_lambda_generate_prompt:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create generate_prompt zip file
        run: |
          cd src/lambda/generate_prompt
          zip -r generate_prompt .
      - name: Update generate_prompt function
        run: |
          aws lambda update-function-code \
          --function-name generate_prompt \
          --zip-file fileb://src/lambda/generate_prompt/generate_prompt.zip \
          --publish

  update_lambda_login:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Substitute secrets in password.py
        run: |
          sed -i "s/rds_host = \"secret\"/rds_host = \"${{ secrets.RDS_HOST }}\"/g" src/lambda/login/password.py
          sed -i "s/db_username = \"secret\"/db_username = \"${{ secrets.DB_USERNAME }}\"/g" src/lambda/login/password.py
          sed -i "s/db_password = \"secret\"/db_password = \"${{ secrets.DB_PASSWORD }}\"/g" src/lambda/login/password.py
          sed -i "s/db_name = \"secret\"/db_name = \"${{ secrets.DB_NAME }}\"/g" src/lambda/login/password.py
          sed -i "s/userpool = \"secret\"/userpool = \"${{ secrets.USERPOOL }}\"/g" src/lambda/login/password.py
      - name: Create login zip file 
        run: |
          cd src/lambda/login
          zip -r login.zip .
      - name: Update login function
        run: |
          aws lambda update-function-code \
          --function-name login \
          --zip-file fileb://src/lambda/login/login.zip \
          --publish

  update_lambda_delete_account:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create delete_account zip file 
        run: |
          cd src/lambda/delete_account
          zip -r delete_account.zip .
      - name: Update delete_account function
        run: |
          aws lambda update-function-code \
          --function-name delete_account \
          --zip-file fileb://src/lambda/delete_account/delete_account.zip \
          --publish

  update_lambda_delete_picture:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create delete_picture zip file 
        run: |
          cd src/lambda/delete_picture
          zip -r delete_picture.zip .
      - name: Update delete_picture function
        run: |
          aws lambda update-function-code \
          --function-name delete_picture \
          --zip-file fileb://src/lambda/delete_picture/delete_picture.zip \
          --publish

  update_lambda_get_account_info:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create get_account_info zip file 
        run: |
          cd src/lambda/get_account_info
          zip -r get_account_info.zip .
      - name: Update get_account_info function
        run: |
          aws lambda update-function-code \
          --function-name get_account_info \
          --zip-file fileb://src/lambda/get_account_info/get_account_info.zip \
          --publish

  update_lambda_get_feed:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create get_feed zip file 
        run: |
          cd src/lambda/get_feed
          zip -r get_feed.zip .
      - name: Update get_feed function
        run: |
          aws lambda update-function-code \
          --function-name get_feed \
          --zip-file fileb://src/lambda/get_feed/get_feed.zip \
          --publish

  update_lambda_logout:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create logout zip file 
        run: |
          cd src/lambda/logout
          zip -r logout.zip .
      - name: Update logout function
        run: |
          aws lambda update-function-code \
          --function-name logout \
          --zip-file fileb://src/lambda/logout/logout.zip \
          --publish

  update_lambda_upload_picture:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create upload_picture zip file 
        run: |
          cd src/lambda/upload_picture
          zip -r upload_picture.zip .
      - name: Update upload_picture function
        run: |
          aws lambda update-function-code \
          --function-name upload_picture \
          --zip-file fileb://src/lambda/upload_picture/upload_picture.zip \
          --publish

  update_lambda_new_friend: 
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create new_friend zip file 
        run: |
          cd src/lambda/new_friend 
          zip -r new_friend.zip . 
      - name: Update new_friend function 
        run: |
          aws lambda update-function-code \
          --function-name new_friend \ # Change this line
          --zip-file fileb://src/lambda/new_friend/new_friend.zip \ 
          --publish 

  update_lambda_remove_friend: 
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create remove_friend zip file 
        run: |
          cd src/lambda/remove_friend 
          zip -r remove_friend.zip . 
      - name: Update remove_friend function 
        run: |
          aws lambda update-function-code \
          --function-name remove_friend \ # Change this line
          --zip-file fileb://src/lambda/remove_friend/remove_friend.zip \ 
          --publish 

