name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -la

  configure_dep:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          sudo apt-get install awscli
      - run: |
          pwd
          ls -la

  update_lambda_test:
    runs-on: ubuntu-latest
    needs: [checkout, configure_dep]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update only on changes in src/lambda/test
        id: check-changes-test1
        run: |
          current_commit_sha=${{ github.sha }}
          parent_commit_sha=$(git rev-parse "${current_commit_sha}^")
          git diff --exit-code $parent_commit_sha $current_commit_sha -- src/lambda/test
          retval=$?
          if [ $retval == 1 ]; then
            echo "Changes detected in src/lambda/test. Proceeding with the workflow."
          else
            echo "No changes in src/lambda/test. Skipping the workflow."
            exit 78
          fi
        continue-on-error: true
      - name: Configure AWS Credentials
        if: success() && steps.check-changes-test1.outcome == 'success'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create test zip file 
        if: success() && steps.check-changes-test1.outcome == 'success'
        run: |
          cd src/lambda/test
          zip -r test.zip .
      - name: Update test function
        if: success() && steps.check-changes-test1.outcome == 'success'
        run: |
          aws lambda update-function-code \
          --function-name test \
          --zip-file fileb://src/lambda/test/test.zip
